api_platform:
    title: Hello API Platform
    version: 1.0.0
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
        html: ['text/html']
        multipart: ['multipart/form-data']
    docs_formats:
        jsonld: ['application/ld+json', 'application/json']
        json: ['application/json']
        jsonopenapi: ['application/vnd.openapi+json', 'application/json']
        html: ['text/html']
    patch_formats:
        json: ['application/json']
        jsonld: ['application/ld+json']
        multipart: ['multipart/form-data']
    defaults:
        validation: true
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    keep_legacy_inflector: false
    use_symfony_listeners: true
    swagger:
        api_keys:
            bearer:
                name: Authorization
                type: header
